select 
AIRPORTS.NAME as AIRPORTNAME, 
AIRLINES.NAME as AIRLINENAME, 
SOURCEAIRPORTID, DESTAIRPORTID, 
AIRLINES.AIRLINEID as AIRLINEID, 
ACTIVE, 
STOPS
from AIRPORTS, ROUTES, AIRLINES 
where AIRPORTID = DESTAIRPORTID 
and DESTAIRPORTID = '666' 
and AIRLINES.ACTIVE = 'Y'
ORDER BY STOPS ASC;

-----------------------------------

SELECT * FROM AIRPORTS WHERE CITY='Melbourne';

-----------------------------------

SELECT 
AIRPORTS.NAME as AIRPORTNAME, 
SOURCEAIRPORTID,
DESTAIRPORTID, 
SOURCEAIRPORT, 
DESTAIRPORT, 
AIRLINES.AIRLINEID as AIRLINEID, 
AIRLINES.NAME AS AIRLINENAME, 
ACTIVE 
FROM AIRPORTS, ROUTES, AIRLINES 
WHERE SOURCEAIRPORTID = '3361' 
AND DESTAIRPORTID = '3339' 
AND ACTIVE = 'Y'
LIMIT 100;